### ISSUE TITLE
 stdin: not in gzip format

### ISSUE THREAD

**Issue by herrdeh** [sobrus/FastLacellsGenerator#1]
I couldnt create a database, neither as user, nor as root:

~$ ./GSM-ortung.sh 
Downloading data
gzip: stdin: not in gzip format

~$ sudo ./GSM-ortung.sh 
Downloading data
gzip: stdin: not in gzip format

What can I do?

**Comment by sobrus** [comment]
It seems like you are not downloading the proper zip file from either Mozilla or OCID. Probably OCID is making problems, so:

Please make sure that
a) you have correctly set up your OpenCellID API Key
b) you are not using the same key more than once per day (without changing the key, you can run this script only once daily)

**Comment by herrdeh** [comment]
My computer didnt habe sqlite3 installed - and there may have been a problem with the download for 1 days or two. In the meanwhile, generating the database ran through.
Tks!
