### ISSUE TITLE
Error on dowloading from mozilla

### ISSUE THREAD

**Issue by ghost** [sobrus/FastLacellsGenerator#11]
From terminal:
"
Loading config from ./config
Downloading data

gzip: stdin: unexpected end of file
Download error
"

**Comment by sobrus** [comment]
Hi, 

Yes, mozilla download link doesn't seem to work anymore.
But I don't see any download links provided at
https://location.services.mozilla.com/downloads
either.

So I'm unable to fix it :( Maybe they are changing something, or stopped providing data (I hope they didn't).

We have to wait until MLS data is available for download again.

**Comment by IzzySoft** [comment]
Funny. Since when is that? A week ago it still worked for me (`cron.monthly` run). And they still accept uploads via TowerCollector…

**Comment by jensMF** [comment]
There is a new Link:
https://d3r3tk5171bc5t.cloudfront.net/export/MLS-full-cell-export-2019-05-07T000000.csv.gz

**Comment by ghost** [comment]
Yes new link fixed the issue!

**Comment by IzzySoft** [comment]
@jensMF mind making a PR for @sobrus to merge?

**Comment by IzzySoft** [comment]
Nevermind, did it for you (credits given) :smiley:

Thanks for finding and providing the new URL! Tested out fine for me as well.
