### ISSUE TITLE
add warning of file download size

### ISSUE THREAD

**Issue by robinpaulson** [sobrus/FastLacellsGenerator#4]
From what I can gather, the script downloads the entire database from opencellid and then filters for country/operator codes. The database appears to be around 700MB, which I think is a bit more than a programme should do without warning. Could you add a line to the script (displayed on screen as it runs) which will inform the user of this? It could be blocking or not, I think either would be fine.

Cheers

**Comment by sobrus** [comment]
No, it filters the database during the download process (so you have only pre-filtered data on disk).
I intend this script to be as small and simple as possible, so anyone can modify it for his/her purposes (in fact, I also use highly modified version for automatic database generation for my smartphone every week).

So, I don't want to add any new functionality here apart from simply generating the database.
