### ISSUE TITLE
The script doesn't work anymore

### ISSUE THREAD

**Issue by tecufanujacu** [sobrus/FastLacellsGenerator#9]
From April 2018 the script has stopped working and I have this error:

gzip: stdin: unexpected end of file
Download error

**Comment by IzzySoft** [comment]
Could it be just you? I had noticed if it failed since April, so for me it has not. Mind mentioning what databases you are using? I have OpenCellID and Mozilla active here.

**Comment by sobrus** [comment]
And what configuration are you using (directories, countries, radio types etc)?

I haven't been using it since october, since unfortunately I cannot get rid of google on my new phone :/
But I will have a look.

**Comment by tecufanujacu** [comment]
You all are right, some strange thing is happening. I have this script on my personal server from February 2017 and thanks to cron every Monday at 4 AM it has always generated the new db. It stopped working at April 2018 but only now I have noticed that if I run it manually it works without problems. The problem seems to be that it fails to download something at 4 AM on Monday. I have to do some test.

**Comment by tecufanujacu** [comment]
You all are right, some strange thing is happening. I have this script on my personal server from February 2017 and thanks to cron every Monday at 4 AM it has always generated the new db from all the three sources. It stopped working at April 2018 but only now I have noticed that if I run it manually it works without problems. The problem seems to be that it fails to download something at 4 AM on Monday. For example the past Monday it has started downloading the files and in fact in /tmp I have:

253K rco.csv.gz
26M ocid.csv.gz (when it should be almost 900M)
and I doesnt' have mozilla.csv.gz

it seems that it fails to download ocid.csv.gz.
Sunday, instead, I manually executed the scipt at 19 PM and everything has worked.
I have to do some test.

**Comment by tecufanujacu** [comment]
You all are right, some strange thing is happening. I have this script on my personal server from February 2017 and thanks to cron every Monday at 4 AM it has always generated the new db from all the three sources. It stopped working at April 2018 but only now I have noticed that if I run it manually it works without problems. The problem seems to be that it fails to download something at 4 AM on Monday. For example the past Monday it has started downloading the files and in fact in /tmp I have:

253K rco.csv.gz
26M ocid.csv.gz (when it should be almost 900M)
and I don't have have mozilla.csv.gz

it seems that it fails to download ocid.csv.gz.
Sunday, instead, I manually executed the scipt at 19 PM and everything has worked.
I have to do some test.

**Comment by IzzySoft** [comment]
That might indeed make a difference. My cron job runs at 7am CET. No probs with either OCID nor MOZ then. Maybe just move the job ± 1h?

**Comment by sobrus** [comment]
Or cron job is killed because it takes too long (it would be strange, but for example systemd can kill init scripts due to "timeout").

**Comment by tecufanujacu** [comment]
No, the problem isn't for sure caused by a timeout.
At the moment I'm trying the script at different hours but I'm limited at two test for day from ocid token.
P.S.: my hour too is at CET.

**Comment by tecufanujacu** [comment]
Ok, after several test at same hour in different week's days I can tell that everything works.
Sorry for bothering you.
I close the issue.

**Comment by IzzySoft** [comment]
It never hurts to ask – unless you ask for hurt :rofl: Glad to see the problem's gone!

**Comment by IzzySoft** [comment]
@sobrus 

> I haven't been using it since october, since unfortunately I cannot get rid of google on my new phone :/

That's no reason not to use it. I have one device where I use UnifiedNLP despite of "Big G" being aboard. Logcat confirmed location is provided that way, and G not asked for it.

**Comment by sobrus** [comment]
@IzzySoft  did you modify your system in any way?
From what I know (according to Microg project page), I would need Xposed Framework.
But I will try.
I also wonder if it works with google nlp services disabled, since having both providers makes little sense.

**Comment by IzzySoft** [comment]
@sobrus either the device supports signature spoofing (one of my devices does), or you'd need the mentioned Xposed module (which I do on another device).

**Comment by sobrus** [comment]
@IzzySoft 
Well I believe my device (Redmi Note 4X, Helio X20 version) doesn't support signature spoofing out of the box. Xposed installer didn't work last time I tried (there's a special version for MIUI) either. 

I've already spend too much time with this phone fixing MIUI bugs and don't want to hassle with it any longer.

**Comment by IzzySoft** [comment]
Which is why I keep my fingers off such heavily modded ROMs – be it Xiaomi's MIUI, Samsung's Touchwiz or whatever. Either there's a "AOSP-like" ROM (like LOS) which I can flash before unboxing – or I look for a different device. Keeps your head from exploding 😉

My current device has official LOS support, so I was able to flash it with [LineageOS-for-microG](https://lineage.microg.org/). No more headaches, works out of the box. Just needed to install (and configure) [LocalGsmNlpBackend](https://f-droid.org/packages/org.fitchfamily.android.gsmlocation/).
